CREATE TABLE produto (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(40) NOT NULL UNIQUE,
    nome VARCHAR2(150) NOT NULL,
    descricao VARCHAR2(500),
    categoria_id NUMBER(19) NOT NULL REFERENCES categoria(id),
    colecao_id NUMBER(19) REFERENCES colecao(id),
    fornecedor_id NUMBER(19) REFERENCES fornecedor(id),
    preco_venda NUMBER(12,2) NOT NULL,
    custo_medio NUMBER(12,2) DEFAULT 0 NOT NULL,
    quantidade_estoque NUMBER(10) DEFAULT 0 NOT NULL,
    estoque_minimo NUMBER(10) DEFAULT 0 NOT NULL,
    version NUMBER(19) DEFAULT 0 NOT NULL,
    ativo NUMBER(1,0) DEFAULT 1 NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
);
