CREATE TABLE movimentacao_estoque (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id NUMBER(19) NOT NULL REFERENCES produto(id),
    funcionario_id NUMBER(19) NOT NULL REFERENCES funcionario(id),
    quantidade NUMBER(10) NOT NULL,
    observacao VARCHAR2(255),
    data_movimentacao TIMESTAMP NOT NULL
);

CREATE TABLE entrada (
    id NUMBER(19) PRIMARY KEY REFERENCES movimentacao_estoque(id),
    custo_unitario NUMBER(12,2) NOT NULL,
    fornecedor_id NUMBER(19) REFERENCES fornecedor(id)
);

CREATE TABLE saida (
    id NUMBER(19) PRIMARY KEY REFERENCES movimentacao_estoque(id),
    motivo VARCHAR2(20) NOT NULL
);
