CREATE TABLE tentativa_saida_negada (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_codigo VARCHAR2(40 CHAR) NOT NULL,
    funcionario_email VARCHAR2(150 CHAR) NOT NULL,
    quantidade_solicitada NUMBER(10) NOT NULL,
    quantidade_disponivel NUMBER(10) NOT NULL,
    registrada_em TIMESTAMP NOT NULL
);
