db.url=jdbc:oracle:thin:@//oracle:1521/XEPDB1
db.username=estoque
db.password=estoque
db.driver=oracle.jdbc.OracleDriver
hibernate.dialect=org.hibernate.dialect.OracleDialect
flyway.locations=classpath:db/migration/oracle

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=3600000
