CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(40) NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    categoria_id BIGINT NOT NULL REFERENCES categoria(id),
    colecao_id BIGINT REFERENCES colecao(id),
    fornecedor_id BIGINT REFERENCES fornecedor(id),
    preco_venda DECIMAL(12,2) NOT NULL,
    custo_medio DECIMAL(12,2) NOT NULL DEFAULT 0,
    quantidade_estoque INT NOT NULL DEFAULT 0,
    estoque_minimo INT NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
);
