CREATE TABLE movimentacao_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL REFERENCES produto(id),
    funcionario_id BIGINT NOT NULL REFERENCES funcionario(id),
    quantidade INT NOT NULL,
    observacao VARCHAR(255),
    data_movimentacao TIMESTAMP NOT NULL
);

CREATE TABLE entrada (
    id BIGINT PRIMARY KEY REFERENCES movimentacao_estoque(id),
    custo_unitario DECIMAL(12,2) NOT NULL,
    fornecedor_id BIGINT REFERENCES fornecedor(id)
);

CREATE TABLE saida (
    id BIGINT PRIMARY KEY REFERENCES movimentacao_estoque(id),
    motivo VARCHAR(20) NOT NULL
);
