CREATE TABLE tentativa_saida_negada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_codigo VARCHAR(40) NOT NULL,
    funcionario_email VARCHAR(150) NOT NULL,
    quantidade_solicitada INT NOT NULL,
    quantidade_disponivel INT NOT NULL,
    registrada_em TIMESTAMP NOT NULL
);
